### ISSUE TITLE
Schematics

### ISSUE THREAD

**Issue by mplinuxgeek** [TinkerGuy/ESP32-PirateAudio#1]
Hi, is this shared on EasyEDA or can you make the schematics available, I'd love to modify the design to include an SD card so I can build an SD based FLAC/MP3 player because Raspberry Pi Zero's just aren't suitable for long run battery use.

PS the 3.3v is connected to both pin 1 and 17, at least on the newer Pirate Audio I have.

**Comment by TinkerGuy** [comment]
This was my first project with EasyEDA. Unfortunately, I was not yet so familiar with the program and started right away with the PCB design. I did not create a schematic with the program at all. But the design is quite simple, so you can easily draw your own schematic. The PCB design file is located in the EasyEDA folder.

**Comment by mplinuxgeek** [comment]
Just thought I'd share that I got one built, but of all the parts I had on hand I didn't have any 2x20 headers so haven't tested the Pirate Audio hat on it yet.

![image](https://user-images.githubusercontent.com/283878/157330803-9a23867d-6bb5-4699-9dc7-3af63cc0a674.png)

I also came across this as it ticks my SD card requirement and looks like it would be nice for more HATs.
https://www.waveshare.com/esp32-one.htm?sku=19188
